### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by linzhp**
fixed two bugs there: one made git-blame failed sometime (now all git-blame commands could be run without any error in voldemort), the other made update_all virtually not working at all, although cache was still working

I used deepcopy in the first bug fix. Not sure if it is a good practice. Give suggestions if it is bad.

### CODE REVIEW

**Comment by cflewis** [comment]
If deepcopy works, then deepcopy works, I'm not too worried about memory constraints (I got away with pulling in the entirety of the patches table in Hunks :) ).

Otherwise looks good; but try not to use `print` statements, use `printdbg`. That way we're not accidentally writing lines out to people who never care about this stuff! I'll make that change myself.

**Comment by linzhp** [comment]
Yeah, I was trying to use printdbg in most places, but when I was profiling the code, if I use printdbg, and turn on the -g switch, the profiling output would be buried in myriad debug output and hard to pick up. So I decided to use print instead and delete them later when I am done. However, when I was partially done, I guessed those print would be of some use for further optimization, so I hesitated to delete them. I agree that using printdbg or logging.debug is better than print, but how do you deal with such situation?

**Comment by cflewis** [comment]
How does the profiling work now? Do you know? I've not used it myself. It looks like you can run it with just small chunks, see how `Metrics.py` uses it. If it's not suitable, maybe we should look into having some sort of `printprofiler` method.

I'll leave this for now and do the merge as it is here. What's your workload looking like? Do you have time to have a look into the profiling, or should I put an issue in? My goal for the next couple of days is just to get a lot of the small bugs fixed and get the issue list down, so I don't want to do much cvsanaly research right now.

**Comment by linzhp** [comment]
I didn't realize that I could use the existing profiling in cvsanaly at the last week, so instead I printed the time cumulated running time at some critical points in Content.py. Now it makes more sense for me to integrate my tinkering profiling into the existing profiler or define a printprofiler method.

I could have some time working on cvsanaly every weekend. For Content running in single-threaded mode, there's no much I can improve now; for that in multi-threaded mode, I am not good at improving multi-threaded programs, so I hope you or Caitlin could look at it, maybe work with me side by side to improve it. However, since there is a plan to update Content, let's postpone it until it's updated.

Last weekend, I also noticed that HunkBlame was unreasonably slow when running on V8 project, I plan to work on profiling that this weekend, and figure out the profiling stuff by the way.

**Comment by cflewis** [comment]
Alright, there's no hurry (you're allowed to have weekends too ;) ).

I'll file a ticket that we need to fix the profiling in Content to remind us to go back to it.

Re: threading: Threading is tricky, because sometimes you end up spending more time co-ordinating thread overhead than you do if you just ran a single thing. I don't know much about improving the speed either, Caitlin would know best. I think what we should do is once you've taken a look at profiling, just run a number of tests varying the size of the thread pool, and see what works best.

As part of that, I also need to look into timing out commands. Some of them needed killing during the mining, but that's a repositoryhandler problem. I'll file an issue in our repohandler repository too.

**Comment by cflewis** [comment]
Shoot, I accidentally merged into `master`, and Git doesn't let you revert merges easily. I'm going to let that one slide, and just push to develop too. Sorry :(

**Pull request merged**
