### PR TITLE
[Hunks] Catch if hunk is already in database.

### PR DESCRIPTION
**Pull request by apepper**
When a duplicate entry is already present inside the database Hunks crashed. Now it just ignores this hunk.

### CODE REVIEW

**Comment by cflewis** [comment]
Hi Alex,
`execute_statement` in `Database.py` is supposed to catch this sort of failure. 

``` python
def execute_statement(statement, parameters, cursor, db, error_message,
                      exception=Exception):
    """Run a statement. Note that the cursor is *mutable*, and will contain
the results after running.
"""

    if isinstance(db, SqliteDatabase):
        import sqlite3.dbapi2

        try:
            return cursor.execute(statement, parameters)
        except sqlite3.dbapi2.OperationalError as e:
            printerr(error_message + ": %s", (e,))
        except Exception as e:
            raise exception(e)
```

... and the same again for MySQL.

This is supposed to be catching duplicate errors. The idea is that most statements we run in the extensions are likely to fail at some point or another due to things like this, and it should just carry on. Only in the instance of something actually unexpected happening (like the DB being down) should the extension fail out.

If this statement isn't catching the duplicate record problem, then this is the method that should catch it, not the code in Hunks.

Can you amend the exception catcher here to catch whatever exception is coming back when the duplicate goes in?

**Comment by apepper** [comment]
@Lewisham: To be honest I don't really understand, how execute_statement should work. From the current code I understand the following:

When the execution failed with an OperationalError it should print out the message "error_message".
When some other exception occurs, yet another exception (of type exception) should be thrown.

My suggestion:
When a OperationalError occurs, that error should be thrown again.
When another exception occurs the message "error_message" should be printed and NO exception should be thrown.
With this the paramenter "exception" of execute_statement becomes obsolete.

What do you think about this?

**Comment by cflewis** [comment]
Yeah, I don't really have any excuses for the poor commenting of that function.

Here's what is it supposed to do:
1. Call an SQL statement
2. If the statement fails in a predictable way (which for us, is almost always an OperationalError thrown from a duplicate record), continue. This was a refactoring, as almost every statement we ever made in cvsanaly was wrapped in a try/catch looking for an OperationalError, and then skipping over it. It turned a one-line statement into six-lines every single time. That's why I refactored to this method.
3. If the statement fails unpredictably, fail with the exception listed in the argument.

The reason why exception is an argument is to give the flexibility to either fail the whole extension (ExtensionRunError), or to fail in a way that the callee can catch if necessary:

``` python
try:
  execute_extension(..., exception=FooError)
catch FooError as e:
  print "I died!"
```

You and I think about what it should do in reverse. You think an OperationalError should cause a stop, and other exceptions should continue, whereas I think an OperationalError should be continued, and other exceptions raised :)

I guess the question is in what circumstances an OperationalError is thrown. [http://www.python.org/dev/peps/pep-0249/](PEP-249) lists it as:

```
OperationalError

            Exception raised for errors that are related to the
            database's operation and not necessarily under the control
            of the programmer, e.g. an unexpected disconnect occurs,
            the data source name is not found, a transaction could not
            be processed, a memory allocation error occurred during
            processing, etc.  It must be a subclass of DatabaseError.
```

This is maybe a little broad :/

How about this: refactor the method so it has `ignored_exceptions=()`. Current usage is changed to `ignored_exceptions=(MySQLdb.OperationalError, sqlite3.dbapi2.OperationalError)`. The logic for catching would then be:

``` python
try:
    ...
except ignored_exceptions:
    print "foo"
except Exception e:
    raise e
```

I _think_ you can pass a tuple like that to `except`, otherwise you could just catch all exceptions, then check the class of the exception in the handler.

The only slight problem is that to do what I'm saying, both MySQL and sqlite would need to be importable, which might make it useless. Any ideas? :(

**Comment by linzhp** [comment]
The exception of duplicate records is MySQLdb.IntegrityError, so I added this exception and sent another pull request #110

**Comment by apepper** [comment]
Pull request #110 fixes this better then my pull request. So this issue should be fixed.

**Pull request closed without merging**
