### PR TITLE
Add Extension FilePatches

### PR DESCRIPTION
**Pull request by linzhp**
FilePatches extension stores patches for each file at each revision in actions table. It is needed by current work of Shiv and me. As it shares some patch parsing code with Hunks extension, I also refactored Hunks and PatchParser to enable better code reuse. Please review the change to make sure the refactoring did not change any intended behavior of Hunks extension.

### CODE REVIEW

**Comment by cflewis** [comment]
I'm a little confused about what this is doing; can't you go from the action `commit_id` to the patch?

Be careful of editing `PatchParser.py` too much, we got that from the open-source Bazaar project. It is probably worth noting in the comments at the top that the file has our own customizations and shouldn't be "upgraded" to any newer version from Bazaar from this point on.

However, I am sure this is all done for the right reasons, so I am happy for you to do this merge once you've added the comments to `PatchParser.py`.

**Comment by linzhp** [comment]
The FilePatches extension tries to get diff for each file during each commit, so given a commit_id is not enough to get the patch.

OK. I will add the comments

**Comment by apepper** [comment]
I want to argue, that saving the "big" patch files right with one of the most importend "actions" table could let to slowdowns. I would favor to store it together with commit_id and file_id in the "patches" table.

**Comment by linzhp** [comment]
Do you mean storing it in a separate table "file_patches". Using the existing "patches" table doesn't seem to be a good idea, because it will cause redundancy.

**Comment by apepper** [comment]
I would save it in "patches", add a "file_id" to it and rewrite Hunks (if at all necessary) to parse those diffs. Patches currently save the exact same information, only that it's not splited by file.

**Comment by linzhp** [comment]
Good idea, I will make that change

**Pull request closed without merging**
